import Mathlib.Geometry.Manifold.IsManifold.InteriorBoundary
import Mathlib.Geometry.Manifold.SmoothEmbedding
import LeeSmoothLib.Ch01.Sec01_06.Theorem_1_46

/-!
# A `C∞` atlas assembled from compatible half-space charts

This is an internal construction tool for Problem 5-23.  It does not assume a manifold structure
on the fiber: it takes the local charts constructed by the inverse function theorem, makes them
the preferred atlas, and derives the `C∞` manifold instance from their proved transition-map
compatibility.
-/

open Set ChartedSpace
open scoped ContDiff Manifold

noncomputable section

namespace Manifold

universe u

/-- Pointed half-space charts that cover `X` and whose pairwise transitions are genuinely `C∞`. -/
structure CInfinityHalfSpaceChartFamily (k : ℕ) (X : Type u) [TopologicalSpace X] where
  chart : X → OpenPartialHomeomorph X (EuclideanHalfSpace (k + 1))
  mem_source : ∀ x, x ∈ (chart x).source
  compatible : ∀ x y, (chart x).symm.trans (chart y) ∈
    contDiffGroupoid ∞ (𝓡∂ (k + 1))

namespace CInfinityHalfSpaceChartFamily

variable {k : ℕ} {X : Type u} [TopologicalSpace X]

/-- The atlas generated by a compatible pointed family of half-space charts. -/
@[reducible] def chartedSpace (D : CInfinityHalfSpaceChartFamily k X) :
    ChartedSpace (EuclideanHalfSpace (k + 1)) X where
  atlas := {e | ∃ x, e = D.chart x}
  chartAt := D.chart
  mem_chart_source := D.mem_source
  chart_mem_atlas x := ⟨x, rfl⟩

/-- Pairwise `C∞` compatibility of the constructed charts produces the actual `C∞` manifold
instance. -/
theorem isManifold (D : CInfinityHalfSpaceChartFamily k X) :
    let _ : ChartedSpace (EuclideanHalfSpace (k + 1)) X := D.chartedSpace
    IsManifold (𝓡∂ (k + 1)) ∞ X := by
  let cs : ChartedSpace (EuclideanHalfSpace (k + 1)) X := D.chartedSpace
  let _ : ChartedSpace (EuclideanHalfSpace (k + 1)) X := cs
  let hGroupoid : HasGroupoid X (contDiffGroupoid ∞ (𝓡∂ (k + 1))) := by
    refine ⟨?_⟩
    intro e e' he he'
    rcases he with ⟨x, rfl⟩
    rcases he' with ⟨y, rfl⟩
    exact D.compatible x y
  let _ : HasGroupoid X (contDiffGroupoid ∞ (𝓡∂ (k + 1))) := hGroupoid
  exact IsManifold.mk' (𝓡∂ (k + 1)) ∞ X

/-- In the constructed atlas, membership in the manifold boundary is exactly vanishing of the
normal coordinate in the pointed chart selected at the point. -/
theorem mem_boundary_iff_chart_normal_eq_zero
    (D : CInfinityHalfSpaceChartFamily k X) (x : X) :
    let _ : ChartedSpace (EuclideanHalfSpace (k + 1)) X := D.chartedSpace
    x ∈ (𝓡∂ (k + 1)).boundary X ↔ ((D.chart x x).1 0 = 0) := by
  let cs : ChartedSpace (EuclideanHalfSpace (k + 1)) X := D.chartedSpace
  let _ : ChartedSpace (EuclideanHalfSpace (k + 1)) X := cs
  dsimp only
  change (𝓡∂ (k + 1)).IsBoundaryPoint x ↔ ((D.chart x x).1 0 = 0)
  rw [(𝓡∂ (k + 1)).isBoundaryPoint_iff,
    frontier_range_modelWithCornersEuclideanHalfSpace]
  change 0 = (extChartAt (𝓡∂ (k + 1)) x x) 0 ↔ _
  have hx : x ∈ (D.chart x).source := D.mem_source x
  have hchart : chartAt (EuclideanHalfSpace (k + 1)) x = D.chart x := rfl
  rw [show extChartAt (𝓡∂ (k + 1)) x = (D.chart x).extend (𝓡∂ (k + 1)) by
    simp only [extChartAt, hchart]]
  change 0 = (D.chart x x).1 0 ↔ (D.chart x x).1 0 = 0
  exact eq_comm

end CInfinityHalfSpaceChartFamily

section BoundaryCoordinate

variable {d : ℕ} {M : Type u} [TopologicalSpace M]
  [ChartedSpace (EuclideanHalfSpace (d + 1)) M]
  [IsManifold (𝓡∂ (d + 1)) ∞ M]

/-- Any compatible `C∞` half-space chart detects the intrinsic boundary by its normal
coordinate.  This is the chart-independent bridge used for the exact boundary-image theorem. -/
theorem mem_boundary_iff_chart_normal_eq_zero_of_mem_maximalAtlas
    {p : M} {e : OpenPartialHomeomorph M (EuclideanHalfSpace (d + 1))}
    (he : e ∈ IsManifold.maximalAtlas (𝓡∂ (d + 1)) ∞ M)
    (hp : p ∈ e.source) :
    p ∈ (𝓡∂ (d + 1)).boundary M ↔ (e p).1 0 = 0 := by
  have hInterior :
      p ∈ (𝓡∂ (d + 1)).interior M ↔ 0 < (e p).1 0 := by
    constructor
    · intro hpInterior
      have htargetInterior :
          e.extend (𝓡∂ (d + 1)) p ∈ interior (e.extend (𝓡∂ (d + 1))).target :=
        ((𝓡∂ (d + 1)).isInteriorPoint_iff_of_mem_maximalAtlas
          (n := ∞) (by simp) he hp).1 hpInterior
      have hrangeInterior :
          e.extend (𝓡∂ (d + 1)) p ∈ interior (range (𝓡∂ (d + 1))) :=
        OpenPartialHomeomorph.interior_extend_target_subset_interior_range _ htargetInterior
      rw [interior_range_modelWithCornersEuclideanHalfSpace] at hrangeInterior
      change 0 < (e p).1 0 at hrangeInterior
      exact hrangeInterior
    · intro hpPos
      have hrangeInterior :
          e.extend (𝓡∂ (d + 1)) p ∈ interior (range (𝓡∂ (d + 1))) := by
        rw [interior_range_modelWithCornersEuclideanHalfSpace]
        change 0 < (e p).1 0
        exact hpPos
      have htargetInterior :
          e.extend (𝓡∂ (d + 1)) p ∈ interior (e.extend (𝓡∂ (d + 1))).target :=
        e.mem_interior_extend_target (e.map_source hp) hrangeInterior
      exact ((𝓡∂ (d + 1)).isInteriorPoint_iff_of_mem_maximalAtlas
        (n := ∞) (by simp) he hp).2 htargetInterior
  constructor
  · intro hpBoundary
    have hpNotInterior : p ∉ (𝓡∂ (d + 1)).interior M :=
      ((𝓡∂ (d + 1)).isBoundaryPoint_iff_not_isInteriorPoint p).1 hpBoundary
    have hpNotPos : ¬ 0 < (e p).1 0 := fun hpPos ↦ hpNotInterior (hInterior.2 hpPos)
    exact le_antisymm (not_lt.mp hpNotPos) (e p).2
  · intro hpZero
    have hpNotInterior : p ∉ (𝓡∂ (d + 1)).interior M := by
      intro hpInterior
      have hpPos := hInterior.1 hpInterior
      rw [hpZero] at hpPos
      exact lt_irrefl 0 hpPos
    exact ((𝓡∂ (d + 1)).isBoundaryPoint_iff_not_isInteriorPoint p).2 hpNotInterior

end BoundaryCoordinate

section EmbeddedFamily

variable {d k q : ℕ} {M : Type u} [TopologicalSpace M]
  [ChartedSpace (EuclideanHalfSpace (d + 1)) M]
  [IsManifold (𝓡∂ (d + 1)) ∞ M]
variable (S : Set M)

/-- The local data actually produced from the inverse function theorem in Problem 5-23.

This is not an assumption of the final theorem.  It is an internal package joining the newly
constructed fiber charts to compatible ambient charts, including the literal immersion normal
form and preservation of the normal coordinate. -/
structure CInfinityHalfSpaceEmbeddedChartFamily extends
    CInfinityHalfSpaceChartFamily k S where
  ambientChart : S → OpenPartialHomeomorph M (EuclideanHalfSpace (d + 1))
  ambient_mem_source : ∀ x, x.1 ∈ (ambientChart x).source
  ambient_mem_maximalAtlas : ∀ x, ambientChart x ∈
    IsManifold.maximalAtlas (𝓡∂ (d + 1)) ∞ M
  source_subset : ∀ x, (toCInfinityHalfSpaceChartFamily.chart x).source ⊆
    Subtype.val ⁻¹' (ambientChart x).source
  equiv : S →
    (EuclideanSpace ℝ (Fin (k + 1)) × EuclideanSpace ℝ (Fin q)) ≃L[ℝ]
      EuclideanSpace ℝ (Fin (d + 1))
  writtenInExtend : ∀ x,
    EqOn
      (((ambientChart x).extend (𝓡∂ (d + 1))) ∘ Subtype.val ∘
        ((toCInfinityHalfSpaceChartFamily.chart x).extend (𝓡∂ (k + 1))).symm)
      ((equiv x) ∘ (·, 0))
      ((toCInfinityHalfSpaceChartFamily.chart x).extend (𝓡∂ (k + 1))).target
  normal_eq : ∀ x,
    ((toCInfinityHalfSpaceChartFamily.chart x x).1 0) =
      ((ambientChart x x.1).1 0)

namespace CInfinityHalfSpaceEmbeddedChartFamily

variable {S : Set M}

/-- Assemble the internal local normal forms into the requested explicit `C∞` manifold pair,
smooth embedding, and exact boundary identity. -/
theorem exists_structure_embedding_and_boundary
    (D : CInfinityHalfSpaceEmbeddedChartFamily (d := d) (k := k) (q := q) S) :
    ∃ cs : ChartedSpace (EuclideanHalfSpace (k + 1)) S,
      ∃ hs : IsManifold (𝓡∂ (k + 1)) ∞ S,
        let _ : ChartedSpace (EuclideanHalfSpace (k + 1)) S := cs
        let _ : IsManifold (𝓡∂ (k + 1)) ∞ S := hs
        IsSmoothEmbedding (𝓡∂ (k + 1)) (𝓡∂ (d + 1)) ∞
            (Subtype.val : S → M) ∧
          Subtype.val '' (𝓡∂ (k + 1)).boundary S =
            S ∩ (𝓡∂ (d + 1)).boundary M := by
  let A := D.toCInfinityHalfSpaceChartFamily
  let cs : ChartedSpace (EuclideanHalfSpace (k + 1)) S := A.chartedSpace
  refine ⟨cs, ?_⟩
  let _ : ChartedSpace (EuclideanHalfSpace (k + 1)) S := cs
  let hs : IsManifold (𝓡∂ (k + 1)) ∞ S := A.isManifold
  refine ⟨hs, ?_⟩
  let _ : IsManifold (𝓡∂ (k + 1)) ∞ S := hs
  have hImmersionOfComplement :
      IsImmersionOfComplement (EuclideanSpace ℝ (Fin q))
        (𝓡∂ (k + 1)) (𝓡∂ (d + 1)) ∞ (Subtype.val : S → M) := by
    intro x
    refine IsImmersionAtOfComplement.mk_of_charts
      (D.equiv x) (A.chart x) (D.ambientChart x)
      (A.mem_source x) (D.ambient_mem_source x) ?_ (D.ambient_mem_maximalAtlas x)
      (D.source_subset x) (D.writtenInExtend x)
    exact IsManifold.subset_maximalAtlas ⟨x, rfl⟩
  have hEmbedding :
      IsSmoothEmbedding (𝓡∂ (k + 1)) (𝓡∂ (d + 1)) ∞
        (Subtype.val : S → M) :=
    ⟨hImmersionOfComplement.isImmersion, Topology.IsEmbedding.subtypeVal⟩
  refine ⟨hEmbedding, ?_⟩
  ext y
  constructor
  · rintro ⟨x, hxBoundary, rfl⟩
    have hxZero : (A.chart x x).1 0 = 0 :=
      (A.mem_boundary_iff_chart_normal_eq_zero x).1 hxBoundary
    have hxAmbientZero : (D.ambientChart x x.1).1 0 = 0 := by
      rw [← D.normal_eq x]
      exact hxZero
    exact ⟨x.2,
      (mem_boundary_iff_chart_normal_eq_zero_of_mem_maximalAtlas
        (D.ambient_mem_maximalAtlas x) (D.ambient_mem_source x)).2 hxAmbientZero⟩
  · rintro ⟨hyS, hyBoundary⟩
    let x : S := ⟨y, hyS⟩
    have hxAmbientZero : (D.ambientChart x x.1).1 0 = 0 :=
      (mem_boundary_iff_chart_normal_eq_zero_of_mem_maximalAtlas
        (D.ambient_mem_maximalAtlas x) (D.ambient_mem_source x)).1 hyBoundary
    have hxZero : (A.chart x x).1 0 = 0 := by
      rw [D.normal_eq x]
      exact hxAmbientZero
    refine ⟨x, (A.mem_boundary_iff_chart_normal_eq_zero x).2 hxZero, rfl⟩

end CInfinityHalfSpaceEmbeddedChartFamily

end EmbeddedFamily

end Manifold
