import PoincareConjecture

#print axioms PoincareConjecture.Topology.FiberSaturation.preimage_fiberSaturated_of_ambient_frontier
#print axioms PoincareConjecture.Topology.FiberSaturation.ambient_fiber_trichotomy
#print axioms PoincareConjecture.Topology.FiberSaturation.connectedComponentIn_univ_prod
#print axioms PoincareConjecture.Topology.FiberSaturation.component_eq_univ_prod_image
#print axioms PoincareConjecture.Topology.FiberSaturation.frontier_component_fiberSaturated
#print axioms PoincareConjecture.Topology.FiberSaturation.component_open_interval
#print axioms PoincareConjecture.Topology.FiberSaturation.embedding_image_connectedComponentIn
#print axioms PoincareConjecture.Topology.FiberSaturation.continuous_collarInteriorMap
#print axioms PoincareConjecture.Topology.FiberSaturation.isEmbedding_collarInteriorMap
#print axioms PoincareConjecture.Topology.FiberSaturation.collarInterior_frontierSaturated
#print axioms PoincareConjecture.Topology.FiberSaturation.collar_component_interval
#print axioms PoincareConjecture.Topology.FiberSaturation.embedded_collar_component_interval
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_closed_collar_saturation
#print axioms PoincareConjecture.Topology.FiberSaturation.frontier_componentIn_subset
#print axioms PoincareConjecture.Topology.FiberSaturation.collar_component_frontier_subset_ambient

#check @PoincareConjecture.Topology.FiberSaturation.sphere_closed_collar_saturation
#check @PoincareConjecture.Topology.FiberSaturation.collar_component_frontier_subset_ambient
