import PoincareConjecture

#print axioms PoincareConjecture.Topology.FiberSaturation.fiberSaturated_of_frontier
#print axioms PoincareConjecture.Topology.FiberSaturation.FiberSaturated.eq_univ_prod_image
#print axioms PoincareConjecture.Topology.FiberSaturation.eq_univ_prod_image_of_frontier
#print axioms PoincareConjecture.Topology.FiberSaturation.exists_open_base
#print axioms PoincareConjecture.Topology.FiberSaturation.fiberSaturated_univ_prod
#print axioms PoincareConjecture.Topology.FiberSaturation.frontier_fiberSaturated_univ_prod
#print axioms PoincareConjecture.Topology.FiberSaturation.open_connected_eq_Ioo
#print axioms PoincareConjecture.Topology.FiberSaturation.exists_interval_of_compact_closure
#print axioms PoincareConjecture.Topology.FiberSaturation.exists_open_ordConnected_base
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere2_connectedSpace
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_neck_fiber_saturation
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_neck_two_frontier_spheres
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_neck_open_interval

#check @PoincareConjecture.Topology.FiberSaturation.sphere_neck_open_interval
#check @PoincareConjecture.Topology.FiberSaturation.sphere_neck_two_frontier_spheres

#print axioms PoincareConjecture.Topology.FiberSaturation.fiber_saturation_from_spherical_frontier
#print axioms PoincareConjecture.Topology.FiberSaturation.exists_closed_cylinder
#print axioms PoincareConjecture.Topology.FiberSaturation.neck_coordinates_cylinder
#check @PoincareConjecture.Topology.FiberSaturation.fiber_saturation_from_spherical_frontier
#check @PoincareConjecture.Topology.FiberSaturation.neck_coordinates_cylinder


#print axioms PoincareConjecture.Topology.FiberSaturation.preimage_fiberSaturated_of_ambient_frontier
#print axioms PoincareConjecture.Topology.FiberSaturation.ambient_fiber_trichotomy
#print axioms PoincareConjecture.Topology.FiberSaturation.connectedComponentIn_univ_prod
#print axioms PoincareConjecture.Topology.FiberSaturation.component_eq_univ_prod_image
#print axioms PoincareConjecture.Topology.FiberSaturation.frontier_component_fiberSaturated
#print axioms PoincareConjecture.Topology.FiberSaturation.component_open_interval
#print axioms PoincareConjecture.Topology.FiberSaturation.embedding_image_connectedComponentIn
#print axioms PoincareConjecture.Topology.FiberSaturation.continuous_collarInteriorMap
#print axioms PoincareConjecture.Topology.FiberSaturation.isEmbedding_collarInteriorMap
#print axioms PoincareConjecture.Topology.FiberSaturation.collarInterior_frontierSaturated
#print axioms PoincareConjecture.Topology.FiberSaturation.collar_component_interval
#print axioms PoincareConjecture.Topology.FiberSaturation.embedded_collar_component_interval
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_closed_collar_saturation
#print axioms PoincareConjecture.Topology.FiberSaturation.frontier_componentIn_subset
#print axioms PoincareConjecture.Topology.FiberSaturation.collar_component_frontier_subset_ambient

#check @PoincareConjecture.Topology.FiberSaturation.sphere_closed_collar_saturation
#check @PoincareConjecture.Topology.FiberSaturation.collar_component_frontier_subset_ambient

#print axioms PoincareConjecture.Topology.FiberSaturation.relativeClosedCylinderHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.relativeClosedCylinderUnitHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_product_closure_homeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.neck_closure_homeomorph_unitCylinder
#print axioms PoincareConjecture.Topology.FiberSaturation.componentIn_disjoint_closed_union
#print axioms PoincareConjecture.Topology.FiberSaturation.componentIn_finite_disjoint_closed
#print axioms PoincareConjecture.Topology.FiberSaturation.componentIn_two_fibers
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_product_two_frontier_components
#print axioms PoincareConjecture.Topology.FiberSaturation.relative_fiber_boundary_pairing_product

#check @PoincareConjecture.Topology.FiberSaturation.relative_fiber_boundary_pairing_product

#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.deck
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.deck_zero
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.deck_add
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.orbitSetoid
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.Space
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_eq_iff
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_deck
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.continuous_proj
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.preimage_proj_image
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.isOpenMap_proj
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.integer_shift_zero
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_injOn_closedStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.period_endpoint_identification
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_injOn_closedStrip_iff
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_isOpenEmbedding_openStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_isEmbedding_closedStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.closedStripHomeomorphImage
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.blueprint_endpoint_convention
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.image_period_closedStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.closure_image_period_openStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.frontier_closure_image_period_empty
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.width_le_period_of_disjoint
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.width_lt_period_of_disjoint_frontier_closure
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.closedStrip_embeds_of_disjoint_frontier_closure
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.deck_image_preimage
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.openStrip_ne_deck_image
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.lifted_strip_component_disjoint
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.lifted_strip_component_width_lt

#check @PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_injOn_closedStrip_iff
#check @PoincareConjecture.Topology.FiberSaturation.MappingTorus.lifted_strip_component_width_lt


#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_surjective
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.base_shift_mem_iff
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.isOpen_real_component
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.lifted_component_isOpen
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.periodic_component_bounded
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.lifted_component_finite_strip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_image_deck
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.component_images_eq_of_inter
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.image_lifted_component_eq
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.image_period_halfOpenStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.image_closedStrip_eq_compl_gap
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.isClosed_image_closedStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.closure_image_openStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.closedCylinderUnitHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.region_short_strip
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.region_closure_homeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.frontier_closure_eq_of_regularOpen
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.sphere_bundle_quotient_regular_region

#check @PoincareConjecture.Topology.FiberSaturation.MappingTorus.sphere_bundle_quotient_regular_region


#print axioms PoincareConjecture.Topology.FiberSaturation.regularOpen_of_frontier_closure_eq
#print axioms PoincareConjecture.Topology.FiberSaturation.HasAmbientModelCharts
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicInterior_iff_ambientInterior
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicBoundary_iff_ambientFrontier
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicInterior_image_eq
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicBoundary_image_eq
#print axioms PoincareConjecture.Topology.FiberSaturation.regularOpen_of_intrinsicBoundary_eq
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicBoundary_eq_frontier_iff_regularOpen
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_quotient_region_of_boundaryCharts
#print axioms PoincareConjecture.Topology.FiberSaturation.closedHalfSpace
#print axioms PoincareConjecture.Topology.FiberSaturation.closedHalfSpace_chartedSpace
#print axioms PoincareConjecture.Topology.FiberSaturation.closedHalfSpace_hasAmbientModelCharts
#print axioms PoincareConjecture.Topology.FiberSaturation.closedHalfSpace_boundary_image
#check @PoincareConjecture.Topology.FiberSaturation.sphere_quotient_region_of_boundaryCharts

#print axioms PoincareConjecture.Topology.FiberSaturation.embedding_local_set_model
#print axioms PoincareConjecture.Topology.FiberSaturation.exists_codimensionZero_ambient_chart
#print axioms PoincareConjecture.Topology.FiberSaturation.interior_transfer_maximalAtlas
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicInterior_iff_maximalChart
#print axioms PoincareConjecture.Topology.FiberSaturation.intrinsicBoundary_iff_maximalChart
#print axioms PoincareConjecture.Topology.FiberSaturation.smoothEmbedding_interior_iff
#print axioms PoincareConjecture.Topology.FiberSaturation.smoothEmbedding_boundary_iff
#print axioms PoincareConjecture.Topology.FiberSaturation.smoothEmbedding_interior_image
#print axioms PoincareConjecture.Topology.FiberSaturation.smoothEmbedding_boundary_image
#print axioms PoincareConjecture.Topology.FiberSaturation.proper_smoothEmbedding_boundary_image
#print axioms PoincareConjecture.Topology.FiberSaturation.closedDomain_boundary_image
#print axioms PoincareConjecture.Topology.FiberSaturation.regularOpen_of_smoothClosure_boundary
#print axioms PoincareConjecture.Topology.FiberSaturation.smoothClosure_boundary_iff_regularOpen
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_region_of_smoothClosure
#print axioms PoincareConjecture.Topology.FiberSaturation.model_inclusion_smoothEmbedding
#check @PoincareConjecture.Topology.FiberSaturation.sphere_region_of_smoothClosure
#check @PoincareConjecture.Topology.FiberSaturation.proper_smoothEmbedding_boundary_image

#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.circle_eq_iff_integer_shift
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_deck_invariant
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_eq_iff_orbit
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentationLift
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentationLift_proj
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.continuous_presentationLift
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.isOpenMap_presentationLift
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.bijective_presentationLift
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentationHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentationHomeomorph_proj
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentationHomeomorph_unique
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_preimage_inverse_image
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.circleProjection
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.circleProjection_proj
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.continuous_circleProjection
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_fiber_injective
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_isLocalHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.proj_isOpenQuotientMap
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.image_height_fiber
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.canonical_presentationHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_image_cylinder
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_closedStrip_embedding
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_openStrip_embedding
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_isLocalHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.presentation_isOpenQuotientMap
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_presentation_coordinates
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_region_of_presented_smoothClosure
#check @PoincareConjecture.Topology.FiberSaturation.sphere_region_of_presented_smoothClosure

#print axioms PoincareConjecture.Topology.FiberSaturation.diffeomorphOfEmbeddingComparison
#print axioms PoincareConjecture.Topology.FiberSaturation.diffeomorphOfEmbeddingComparison_apply
#print axioms PoincareConjecture.Topology.FiberSaturation.diffeomorphOfEqualEmbeddingRange
#print axioms PoincareConjecture.Topology.FiberSaturation.realTranslation
#print axioms PoincareConjecture.Topology.FiberSaturation.realReflection
#print axioms PoincareConjecture.Topology.FiberSaturation.realDiffeomorph_mem_maximalAtlas
#print axioms PoincareConjecture.Topology.FiberSaturation.Icc_subtype_smoothEmbedding
#print axioms PoincareConjecture.Topology.FiberSaturation.iccDiffeomorphUnit
#print axioms PoincareConjecture.Topology.FiberSaturation.cylinder_inclusion_smoothEmbedding
#print axioms PoincareConjecture.Topology.FiberSaturation.cylinderDiffeomorphUnit
#print axioms PoincareConjecture.Topology.FiberSaturation.cylinderDiffeomorphUnit_apply
#print axioms PoincareConjecture.Topology.FiberSaturation.comparison_inverse_contMDiff
#print axioms PoincareConjecture.Topology.FiberSaturation.diffeomorphOfLocalDiffeomorphComparison
#print axioms PoincareConjecture.Topology.FiberSaturation.diffeomorphOfLocalDiffeomorphComparison_apply
#print axioms PoincareConjecture.Topology.FiberSaturation.presented_region_closedStrip
#print axioms PoincareConjecture.Topology.FiberSaturation.sphere_region_diffeomorph_of_smoothPresentation
#print axioms PoincareConjecture.Topology.FiberSaturation.product_region_diffeomorph
#check @PoincareConjecture.Topology.FiberSaturation.sphere_region_diffeomorph_of_smoothPresentation
#check @PoincareConjecture.Topology.FiberSaturation.product_region_diffeomorph

#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cover
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.Lifted
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutTrivialization
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutTrivialization_covers
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap_proj
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.continuous_cutMap
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutFiberChart
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutFiberChart_apply
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutFiberChart_symm
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap_fiber_injective
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.fiberTransport
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.fiberTransport_mk
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap_eq_fiberChart
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap_range_fiber
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.surjective_cutMap
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.monodromy
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap_endpoints
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.monodromy_unique
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.circle_Icc_eq_or_endpoints
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.Seam
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.cutMap_eq_iff_seam
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.ClosedMappingTorus
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedDescent
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedDescent_mk
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.continuous_closedDescent
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.bijective_closedDescent
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedBundleHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedBundleHomeomorph_mk
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.abstract_bundle_closed_mappingTorus
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.abstract_sphere_bundle_closed_mappingTorus

#check @PoincareConjecture.Topology.FiberSaturation.CircleBundle.abstract_sphere_bundle_closed_mappingTorus

#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.space_t2Space
#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.space_compactSpace
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.fundamentalProjection
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.continuous_fundamentalProjection
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.fundamentalProjection_fiber_injective
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.fundamentalProjection_endpoints
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.surjective_fundamentalProjection
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.fundamentalProjection_eq_iff_seam
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedToReal
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedToReal_mk
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.continuous_closedToReal
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.bijective_closedToReal
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedRealHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedRealHomeomorph_mk
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.closedRealHomeomorph_unique
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realBundleHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realBundleHomeomorph_fundamental
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realBundleHomeomorph_base
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realPresentation
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.continuous_realPresentation
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.surjective_realPresentation
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realPresentation_base
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realPresentation_fiber_injective
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realPresentation_glue
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realPresentation_cut
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.realPresentation_isLocalHomeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.abstract_bundle_real_presentation
#print axioms PoincareConjecture.Topology.FiberSaturation.CircleBundle.abstract_sphere_bundle_real_presentation
#print axioms PoincareConjecture.Topology.FiberSaturation.ProjectionSaturated
#print axioms PoincareConjecture.Topology.FiberSaturation.projectionSaturated_pullback
#print axioms PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_regular_region
#print axioms PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_smoothClosure_region

#check @PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_regular_region
#check @PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_smoothClosure_region

#print axioms PoincareConjecture.Topology.FiberSaturation.MappingTorus.region_frontier_circle_pair
#print axioms PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_frontier_pair
#print axioms PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_fiber_connected
#print axioms PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_boundary_components
#check @PoincareConjecture.Topology.FiberSaturation.abstract_sphere_bundle_boundary_components

#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.seamClamp
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.contDiff_seamClamp
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.seamClamp_eq_self
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.seamClamp_eq_center
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.seamClamp_mem
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.seamClamp_eqOn
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.IsSmoothTrivialization
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.contMDiffOn_coordChange
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.transitionDiffeomorph
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.isSmooth_restrOpen
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.adjust
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.adjust_apply
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.isSmooth_adjust
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.matchNear
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.matchNear_smooth
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.matchNear_eq
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.contMDiffOn_ite_le
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.inverse_eqOn_collar
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.smooth_piecewiseLeOfEq
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.exists_smooth_splice_of_collar
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.exists_smooth_splice
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.exists_smooth_trivialization_Icc
#print axioms PoincareConjecture.Topology.FiberSaturation.SmoothBundle.fiberBundle_exists_smooth_trivialization_Icc

#check @PoincareConjecture.Topology.FiberSaturation.SmoothBundle.exists_smooth_trivialization_Icc
#check @PoincareConjecture.Topology.FiberSaturation.SmoothBundle.fiberBundle_exists_smooth_trivialization_Icc
