import Mathlib
import LeeSmoothLib.Ch01.Sec01.Definition_1_extra_1
import LeeSmoothLib.Ch04.Sec04_21.Example_4_2
import LeeSmoothLib.Ch05.Sec05_28.Definition_5_28_extra_1
import LeeSmoothLib.Ch05.Sec05_30.Definition_5_30_extra_3
import LeeSmoothLib.Verified.LevelSets.RegularValue
import LeeSmoothLib.Ch05.Sec05_32.Definition_5_32_extra_2
-- Declarations for this item will be appended below by the statement pipeline.

open Manifold
open scoped ContDiff Manifold

noncomputable section

-- Use Mathlib's canonical open-subtype charts consistently.  The project-level
-- topological-manifold wrapper supplies an extensionally equivalent competing instance.
attribute [-instance] TopologicalSpace.Opens.topologicalManifold

local notation "R2" => EuclideanSpace ℝ (Fin 2)
local notation "R3" => EuclideanSpace ℝ (Fin 3)

-- Semantic recall note: `lean_leansearch` was unavailable in this environment, so the statement
-- shape was fixed from the local `Set.IsLocalDefiningMapOn`, `IsEmbeddedSubmanifold`, and
-- `torus_revolution_surface` APIs already present in this repository.

/-- The right half-plane `H = {(r,z) : r > 0}` used for generating curves of surfaces of
revolution. -/
def surface_revolution_half_plane : Set R2 :=
  {p | 0 < p 0}

/-- Membership in `surface_revolution_half_plane` is the positivity of the radial coordinate. -/
theorem mem_surface_revolution_half_plane_iff {p : R2} :
    p ∈ surface_revolution_half_plane ↔ 0 < p 0 := Iff.rfl

/-- The cylindrical-coordinate projection `(x,y,z) ↦ (sqrt (x^2 + y^2), z)`. -/
def surface_revolution_cylindrical (p : R3) : R2 :=
  WithLp.toLp 2 ![Real.sqrt (p 0 ^ 2 + p 1 ^ 2), p 2]

/-- The cylindrical-coordinate projection has the expected explicit coordinates. -/
theorem surface_revolution_cylindrical_apply (p : R3) :
    surface_revolution_cylindrical p =
      WithLp.toLp 2 ![Real.sqrt (p 0 ^ 2 + p 1 ^ 2), p 2] := rfl

/-- The surface of revolution generated by a subset `C ⊆ H`. -/
def surface_of_revolution (C : Set R2) : Set R3 :=
  {p | surface_revolution_cylindrical p ∈ C}

/-- Membership in `surface_of_revolution C` means that the cylindrical point
`(sqrt (x^2 + y^2), z)` lies in `C`. -/
theorem mem_surface_of_revolution_iff {C : Set R2} {p : R3} :
    p ∈ surface_of_revolution C ↔ surface_revolution_cylindrical p ∈ C := Iff.rfl

/-- The lifted open neighborhood `Ũ` on which the local defining function for the surface of
revolution is defined. -/
theorem isOpen_surface_of_revolution_local_domain (U : TopologicalSpace.Opens R2) :
    IsOpen {p : R3 | surface_revolution_cylindrical p ∈ U} := by
  apply U.2.preimage
  unfold surface_revolution_cylindrical
  refine (PiLp.continuous_toLp 2 (fun _ : Fin 2 ↦ ℝ)).comp (continuous_pi fun i ↦ ?_)
  fin_cases i
  · exact Real.continuous_sqrt.comp
      (((PiLp.continuous_apply 2 (fun _ : Fin 3 ↦ ℝ) 0).pow 2).add
        ((PiLp.continuous_apply 2 (fun _ : Fin 3 ↦ ℝ) 1).pow 2))
  · exact PiLp.continuous_apply 2 (fun _ : Fin 3 ↦ ℝ) 2

/-- The open subset `Ũ = {(x,y,z) : (sqrt (x^2 + y^2), z) ∈ U}` attached to an open
`U ⊆ ℝ^2`. -/
def surface_of_revolution_local_domain (U : TopologicalSpace.Opens R2) :
    TopologicalSpace.Opens R3 :=
  ⟨{p : R3 | surface_revolution_cylindrical p ∈ U},
    isOpen_surface_of_revolution_local_domain U⟩

/-- Membership in `surface_of_revolution_local_domain U` is exactly the cylindrical-membership
condition defining `Ũ`. -/
theorem mem_surface_of_revolution_local_domain_iff {U : TopologicalSpace.Opens R2} {p : R3} :
    p ∈ surface_of_revolution_local_domain U ↔ surface_revolution_cylindrical p ∈ U := Iff.rfl

/-- The lifted local defining function `Φ(x,y,z) = φ(sqrt (x^2 + y^2), z)`. -/
def surface_of_revolution_local_defining_function {U : TopologicalSpace.Opens R2}
    (φ : U → ℝ) :
    surface_of_revolution_local_domain U → ℝ :=
  fun p ↦ φ ⟨surface_revolution_cylindrical p.1, p.2⟩

/-- The lifted local defining function is computed by composing `φ` with the cylindrical
projection. -/
theorem surface_of_revolution_local_defining_function_apply {U : TopologicalSpace.Opens R2}
    (φ : U → ℝ) (p : surface_of_revolution_local_domain U) :
    surface_of_revolution_local_defining_function φ p =
      φ ⟨surface_revolution_cylindrical p.1, p.2⟩ := rfl

/-- The generating circle `(r - 2)^2 + z^2 = 1` from the torus example. -/
def torus_revolution_generating_curve : Set R2 :=
  {p | (p 0 - 2) ^ 2 + p 1 ^ 2 = 1}

/-- Membership in `torus_revolution_generating_curve` is the explicit circle equation. -/
theorem mem_torus_revolution_generating_curve_iff {p : R2} :
    p ∈ torus_revolution_generating_curve ↔ (p 0 - 2) ^ 2 + p 1 ^ 2 = 1 := Iff.rfl

namespace Example517

/-- The cylindrical projection is smooth at every point off its axis. -/
private theorem cylindrical_contMDiffAt {p : R3}
    (hp : 0 < surface_revolution_cylindrical p 0) :
    ContMDiffAt (𝓡 3) (𝓡 2) ∞ surface_revolution_cylindrical p := by
  rw [contMDiffAt_iff_contDiffAt]
  have hsqrt : 0 < Real.sqrt (p 0 ^ 2 + p 1 ^ 2) := by
    simpa [surface_revolution_cylindrical, PiLp.toLp_apply] using hp
  have hrad : p 0 ^ 2 + p 1 ^ 2 ≠ 0 := (Real.sqrt_pos.mp hsqrt).ne'
  refine (PiLp.contDiff_toLp (p := 2) (𝕜 := ℝ) (E := fun _ : Fin 2 ↦ ℝ)).contDiffAt.comp p ?_
  rw [contDiffAt_pi]
  intro i
  fin_cases i
  · exact
      (((contDiff_piLp_apply (p := 2) (i := (0 : Fin 3))).contDiffAt.pow 2).add
        ((contDiff_piLp_apply (p := 2) (i := (1 : Fin 3))).contDiffAt.pow 2)).sqrt hrad
  · exact (contDiff_piLp_apply (p := 2) (i := (2 : Fin 3))).contDiffAt

/-- The cylindrical projection, restricted to a lifted positive-radius patch, is smooth. -/
private theorem cylindrical_restrict_contMDiff
    {U : TopologicalSpace.Opens R2}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane) :
    ContMDiff (𝓡 3) (𝓡 2) ∞
      (fun p : surface_of_revolution_local_domain U ↦
        (⟨surface_revolution_cylindrical p.1, p.2⟩ : U)) := by
  have hAmbient :
      ContMDiff (𝓡 3) (𝓡 2) ∞
        (fun p : surface_of_revolution_local_domain U ↦
          surface_revolution_cylindrical p.1) := by
    intro p
    apply contMDiffAt_subtype_iff.2
    apply cylindrical_contMDiffAt
    exact hU p.2
  apply (contMDiff_subtype_val_comp_iff (I := 𝓡 2) (K := 𝓡 3) U _).mp
  exact hAmbient

/-- A radial lift through a fixed point of a lifted patch. -/
private def radialLiftRaw {U : TopologicalSpace.Opens R2}
    (p : surface_of_revolution_local_domain U) (q : R2) : R3 :=
  WithLp.toLp 2
    ![q 0 * p.1 0 / (surface_revolution_cylindrical p.1 0),
      q 0 * p.1 1 / (surface_revolution_cylindrical p.1 0), q 1]

/-- The radial lift is a right inverse to the cylindrical projection on the positive half-plane. -/
private theorem cylindrical_radialLiftRaw
    {U : TopologicalSpace.Opens R2}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (p : surface_of_revolution_local_domain U) (q : U) :
    surface_revolution_cylindrical (radialLiftRaw p q.1) = q.1 := by
  have hpρ : 0 < surface_revolution_cylindrical p.1 0 := hU p.2
  have hqρ : 0 < q.1 0 := hU q.2
  have hpρ_ne : surface_revolution_cylindrical p.1 0 ≠ 0 := hpρ.ne'
  have hpρ_sq :
      (surface_revolution_cylindrical p.1 0) ^ 2 = p.1 0 ^ 2 + p.1 1 ^ 2 := by
    simp only [surface_revolution_cylindrical, PiLp.toLp_apply]
    exact Real.sq_sqrt (by positivity)
  ext i
  fin_cases i
  · change
      Real.sqrt
          ((q.1 0 * p.1 0 / surface_revolution_cylindrical p.1 0) ^ 2 +
            (q.1 0 * p.1 1 / surface_revolution_cylindrical p.1 0) ^ 2) =
        q.1 0
    rw [show
      (q.1 0 * p.1 0 / surface_revolution_cylindrical p.1 0) ^ 2 +
          (q.1 0 * p.1 1 / surface_revolution_cylindrical p.1 0) ^ 2 =
        (q.1 0) ^ 2 by
          field_simp
          nlinarith [hpρ_sq]]
    exact (Real.sqrt_sq_eq_abs (q.1 0)).trans (abs_of_pos hqρ)
  · rfl

/-- The radial lift packaged as a map between the two open patches. -/
private def radialLift
    {U : TopologicalSpace.Opens R2}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (p : surface_of_revolution_local_domain U) (q : U) :
    surface_of_revolution_local_domain U :=
  ⟨radialLiftRaw p q.1, by
    change surface_revolution_cylindrical (radialLiftRaw p q.1) ∈ U
    rw [cylindrical_radialLiftRaw hU p q]
    exact q.2⟩

/-- The radial lift is smooth. -/
private theorem radialLift_contMDiff
    {U : TopologicalSpace.Opens R2}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (p : surface_of_revolution_local_domain U) :
    ContMDiff (𝓡 2) (𝓡 3) ∞ (radialLift hU p) := by
  have hRaw : ContMDiff (𝓡 2) (𝓡 3) ∞ (fun q : U ↦ radialLiftRaw p q.1) := by
    intro q
    apply contMDiffAt_subtype_iff.2
    rw [contMDiffAt_iff_contDiffAt]
    refine (PiLp.contDiff_toLp (p := 2) (𝕜 := ℝ) (E := fun _ : Fin 3 ↦ ℝ)).contDiffAt.comp q.1 ?_
    rw [contDiffAt_pi]
    intro i
    have hpρ_ne : surface_revolution_cylindrical p.1 0 ≠ 0 := (hU p.2).ne'
    fin_cases i
    · change ContDiffAt ℝ ∞
        (fun x : R2 ↦ x 0 * p.1 0 / surface_revolution_cylindrical p.1 0) q.1
      exact
        ((contDiff_piLp_apply (p := 2) (i := (0 : Fin 2))).contDiffAt.mul
          contDiffAt_const).div contDiffAt_const hpρ_ne
    · change ContDiffAt ℝ ∞
        (fun x : R2 ↦ x 0 * p.1 1 / surface_revolution_cylindrical p.1 0) q.1
      exact
        ((contDiff_piLp_apply (p := 2) (i := (0 : Fin 2))).contDiffAt.mul
          contDiffAt_const).div contDiffAt_const hpρ_ne
    · change ContDiffAt ℝ ∞ (fun x : R2 ↦ x 1) q.1
      exact (contDiff_piLp_apply (p := 2) (i := (1 : Fin 2))).contDiffAt
  apply (contMDiff_subtype_val_comp_iff (I := 𝓡 3) (K := 𝓡 2)
    (surface_of_revolution_local_domain U) _).mp
  exact hRaw

/-- The packaged radial lift is a right inverse to the restricted cylindrical projection. -/
private theorem cylindrical_radialLift
    {U : TopologicalSpace.Opens R2}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (p : surface_of_revolution_local_domain U) (q : U) :
    (⟨surface_revolution_cylindrical (radialLift hU p q).1,
      (radialLift hU p q).2⟩ : U) = q := by
  apply Subtype.ext
  exact cylindrical_radialLiftRaw hU p q

/-- At the cylindrical image of its base point, the chosen radial lift returns that base point. -/
private theorem radialLift_base
    {U : TopologicalSpace.Opens R2}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (p : surface_of_revolution_local_domain U) :
    radialLift hU p
        (⟨surface_revolution_cylindrical p.1, p.2⟩ : U) = p := by
  apply Subtype.ext
  ext i
  have hpρ_ne : surface_revolution_cylindrical p.1 0 ≠ 0 := (hU p.2).ne'
  fin_cases i
  · change
      surface_revolution_cylindrical p.1 0 * p.1 0 /
          surface_revolution_cylindrical p.1 0 =
        p.1 0
    field_simp
  · change
      surface_revolution_cylindrical p.1 0 * p.1 1 /
          surface_revolution_cylindrical p.1 0 =
        p.1 1
    field_simp
  · rfl

end Example517

open Example517

/-- Example 5.17 (1): if `φ : U → ℝ` is a local defining function for `C` on an open subset
`U ⊆ H`, then `Φ(x,y,z) = φ (sqrt (x^2 + y^2), z)` is a local defining function for the surface
of revolution `S_C` on the lifted open subset `Ũ`. -/
@[reducible]
def surface_of_revolution_local_defining_map_on
    {C : Set R2} {U : TopologicalSpace.Opens R2} {φ : U → ℝ}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (hφ : Set.IsLocalDefiningMapOn (𝓡 2) 𝓘(ℝ, ℝ) C U φ) :
    Set.IsLocalDefiningMapOn
      (𝓡 3)
      𝓘(ℝ, ℝ)
      (surface_of_revolution C)
      (surface_of_revolution_local_domain U)
      (surface_of_revolution_local_defining_function φ) where
  level := hφ.level
  contMDiff := by
    change ContMDiff (𝓡 3) 𝓘(ℝ, ℝ) ∞
      (fun p : surface_of_revolution_local_domain U ↦
        φ ⟨surface_revolution_cylindrical p.1, p.2⟩)
    exact hφ.contMDiff.comp (cylindrical_restrict_contMDiff hU)
  isLevelSet := by
    ext p
    change
      surface_revolution_cylindrical p.1 ∈ C ↔
        φ ⟨surface_revolution_cylindrical p.1, p.2⟩ = hφ.level
    have hp := Set.ext_iff.mp hφ.isLevelSet
      (⟨surface_revolution_cylindrical p.1, p.2⟩ : U)
    simpa using hp
  surj_mfderiv := by
    intro p hpC
    let g : surface_of_revolution_local_domain U → U :=
      fun x ↦ ⟨surface_revolution_cylindrical x.1, x.2⟩
    let s : U → surface_of_revolution_local_domain U := radialLift hU p
    have hg : ContMDiff (𝓡 3) (𝓡 2) ∞ g := cylindrical_restrict_contMDiff hU
    have hs : ContMDiff (𝓡 2) (𝓡 3) ∞ s := radialLift_contMDiff hU p
    have hΦ :
        ContMDiff (𝓡 3) 𝓘(ℝ, ℝ) ∞
          (surface_of_revolution_local_defining_function φ) := by
      change ContMDiff (𝓡 3) 𝓘(ℝ, ℝ) ∞
        (fun x : surface_of_revolution_local_domain U ↦
          φ ⟨surface_revolution_cylindrical x.1, x.2⟩)
      exact hφ.contMDiff.comp hg
    let q : U := g p
    have hqC : (q : R2) ∈ C := hpC
    have hsurj := hφ.surj_mfderiv q hqC
    intro y
    rcases hsurj y with ⟨v, hv⟩
    refine ⟨mfderiv (𝓡 2) (𝓡 3) s q v, ?_⟩
    have hsbase : s q = p := by
      simpa [s, q, g] using radialLift_base hU p
    have hcomp :
        (surface_of_revolution_local_defining_function φ) ∘ s = φ := by
      funext z
      change φ
          (⟨surface_revolution_cylindrical (radialLift hU p z).1,
            (radialLift hU p z).2⟩ : U) =
        φ z
      rw [cylindrical_radialLift hU p z]
    have hchain :=
      mfderiv_comp q (hΦ.mdifferentiableAt (by simp)) (hs.mdifferentiableAt (by simp))
    rw [hcomp] at hchain
    rw [← hsbase]
    change
      (mfderiv (𝓡 3) 𝓘(ℝ, ℝ)
          (surface_of_revolution_local_defining_function φ) (s q)).comp
          (mfderiv (𝓡 2) (𝓡 3) s q) v =
        y
    rw [← hchain]
    exact hv

/-- The constructed local defining map for the surface of revolution has the same level as the
original local defining map on the generating curve. -/
theorem surface_of_revolution_local_defining_map_on_level
    {C : Set R2} {U : TopologicalSpace.Opens R2} {φ : U → ℝ}
    (hU : (U : Set R2) ⊆ surface_revolution_half_plane)
    (hφ : Set.IsLocalDefiningMapOn (𝓡 2) 𝓘(ℝ, ℝ) C U φ) :
    (surface_of_revolution_local_defining_map_on hU hφ).level = hφ.level := rfl

/-- The fixed linear identification from the scalar target to the Euclidean one-dimensional
model used by the local regular-level theorem. -/
private def surface_revolution_realToR1Equiv :
    ℝ ≃L[ℝ] EuclideanSpace ℝ (Fin 1) :=
  ((EuclideanSpace.equiv (Fin 1) ℝ).trans
    (ContinuousLinearEquiv.funUnique (Fin 1) ℝ ℝ)).symm

private def surface_revolution_realToR1 : ℝ → EuclideanSpace ℝ (Fin 1) :=
  surface_revolution_realToR1Equiv

/-- The scalar-to-`ℝ¹` identification is a smooth submersion. -/
private theorem surface_revolution_realToR1_isSmoothSubmersion :
    IsSmoothSubmersion 𝓘(ℝ, ℝ) (𝓡 1) surface_revolution_realToR1 := by
  refine ⟨?_, ?_⟩
  · simpa [surface_revolution_realToR1] using
      surface_revolution_realToR1Equiv.toContinuousLinearMap.contMDiff
  · intro x
    rw [mfderiv_eq_fderiv]
    have hderiv :
        fderiv ℝ surface_revolution_realToR1 x =
          surface_revolution_realToR1Equiv.toContinuousLinearMap := by
      simpa [surface_revolution_realToR1] using
        (surface_revolution_realToR1Equiv.toContinuousLinearMap.hasFDerivAt (x := x)).fderiv
    rw [hderiv]
    exact surface_revolution_realToR1Equiv.surjective

/-- Postcomposing a scalar local defining map with `ℝ ≃ ℝ¹` preserves all defining-map data. -/
@[reducible] private def localDefiningMap_realToR1
    {m : ℕ} {M : Type*} [TopologicalSpace M]
    [ChartedSpace (EuclideanSpace ℝ (Fin m)) M] [IsManifold (𝓡 m) ∞ M]
    {S : Set M} {U : TopologicalSpace.Opens M} {φ : U → ℝ}
    (hφ : Set.IsLocalDefiningMapOn (𝓡 m) 𝓘(ℝ, ℝ) S U φ) :
    Set.IsLocalDefiningMapOn (𝓡 m) (𝓡 1) S U
      (fun x ↦ surface_revolution_realToR1 (φ x)) where
  level := surface_revolution_realToR1 hφ.level
  contMDiff := by
    convert surface_revolution_realToR1_isSmoothSubmersion.contMDiff.comp hφ.contMDiff using 1
    funext x
    rfl
  isLevelSet := by
    ext x
    have hx := Set.ext_iff.mp hφ.isLevelSet x
    simpa [surface_revolution_realToR1,
      surface_revolution_realToR1Equiv.injective.eq_iff] using hx
  surj_mfderiv := by
    intro x hxS
    have houter :
        MDifferentiableAt 𝓘(ℝ, ℝ) (𝓡 1) surface_revolution_realToR1 (φ x) :=
      surface_revolution_realToR1_isSmoothSubmersion.contMDiff.contMDiffAt.mdifferentiableAt
        (by simp)
    have hinner : MDifferentiableAt (𝓡 m) 𝓘(ℝ, ℝ) φ x :=
      hφ.contMDiff.contMDiffAt.mdifferentiableAt (by simp)
    have hchain := mfderiv_comp x houter hinner
    change Function.Surjective
      (mfderiv (𝓡 m) (𝓡 1) (surface_revolution_realToR1 ∘ φ) x)
    rw [hchain]
    simpa [Function.comp] using!
      (surface_revolution_realToR1_isSmoothSubmersion.surjective_mfderiv (φ x)).comp
        (hφ.surj_mfderiv x hxS)

/-- Example 5.17 (2): if each point of the generating curve `C ⊆ H` admits a local defining
function on an open subset of the half-plane, then the surface of revolution `S_C ⊆ ℝ^3` carries
an honest embedded `C∞` two-manifold structure with the subspace topology.

No global defining function, and in particular no analytic defining function, is assumed.  The
local scalar defining functions are radially lifted by part (1), converted linearly to `ℝ¹`, and
fed to the local regular-level atlas theorem.  The older `IsEmbeddedSubmanifold` owner is not used:
its outer-top inclusion would incorrectly assert analyticity.  The flat graph
`x ↦ if x ≤ 0 then 0 else exp (-1 / x)` is the standard counterexample to that implication. -/
theorem surface_of_revolution_is_embedded_submanifold
    {C : Set R2}
    (_hC : C ⊆ surface_revolution_half_plane)
    (hLocal :
      ∀ p ∈ C,
        ∃ U : TopologicalSpace.Opens R2, p ∈ U ∧
          ∃ _hU : (U : Set R2) ⊆ surface_revolution_half_plane,
            ∃ φ : U → ℝ, Nonempty (Set.IsLocalDefiningMapOn (𝓡 2) 𝓘(ℝ, ℝ) C U φ)) :
    (∃ cs : ChartedSpace R2 (surface_of_revolution C),
      ∃ hs : IsManifold (𝓡 2) ∞ (surface_of_revolution C),
        let _ : ChartedSpace R2 (surface_of_revolution C) := cs
        let _ : IsManifold (𝓡 2) ∞ (surface_of_revolution C) := hs
        IsSmoothEmbedding (𝓡 2) (𝓡 3) ∞
          (Subtype.val : surface_of_revolution C → R3)) := by
  have hSurfaceLocal :
      ∀ p ∈ surface_of_revolution C,
        ∃ V : TopologicalSpace.Opens R3, p ∈ V ∧
          ∃ Φ : V → EuclideanSpace ℝ (Fin 1),
            Nonempty
              (Set.IsLocalDefiningMapOn (𝓡 3) (𝓡 1)
                (surface_of_revolution C) V Φ) := by
    intro p hp
    rcases hLocal (surface_revolution_cylindrical p) hp with
      ⟨U, hpU, hU, φ, ⟨hφ⟩⟩
    let hLift := surface_of_revolution_local_defining_map_on hU hφ
    let V := surface_of_revolution_local_domain U
    let Φ : V → EuclideanSpace ℝ (Fin 1) :=
      fun x ↦ surface_revolution_realToR1
        (surface_of_revolution_local_defining_function φ x)
    refine ⟨V, hpU, Φ, ?_⟩
    exact ⟨localDefiningMap_realToR1 hLift⟩
  simpa using
    (LeeVerifiedLevelSets.LocalRegularLevelSmooth.local_regular_level_set_has_smooth_embedded_structure
      (m := 3) (n := 1) (surface_of_revolution C) (by norm_num) hSurfaceLocal)

/-- Example 5.17 (3): the standard torus of revolution from Example 4.2 is the surface of
revolution generated by the circle `(r - 2)^2 + z^2 = 1` in the half-plane. -/
theorem torus_revolution_surface_eq_surface_of_revolution :
    torus_revolution_surface = surface_of_revolution torus_revolution_generating_curve := by
  ext p
  rfl
