import PoincareConjecture.Basic
import PoincareConjecture.Topology.FiberSaturation.SmoothPeriodicInverse
import PoincareConjecture.Topology.FiberSaturation.NeckCoordinates
import PoincareConjecture.Topology.FiberSaturation.Boundary
import PoincareConjecture.Topology.FiberSaturation.ProductPairing
import PoincareConjecture.Topology.FiberSaturation.TorusComponents
import PoincareConjecture.Topology.FiberSaturation.TorusRegionClassification
import PoincareConjecture.Topology.FiberSaturation.BoundaryModels
import PoincareConjecture.Topology.FiberSaturation.SmoothEmbeddingModels
import PoincareConjecture.Topology.FiberSaturation.PresentedSmoothRegion
import PoincareConjecture.Topology.FiberSaturation.SmoothProductRegion
import PoincareConjecture.Topology.FiberSaturation.AbstractBundleMappingTorus
import PoincareConjecture.Topology.FiberSaturation.AbstractBoundaryPairing
import PoincareConjecture.Topology.FiberSaturation.NativeCirclePullback

import PoincareConjecture.Topology.FiberSaturation.SmoothIntervalTrivialization

import PoincareConjecture.Topology.FiberSaturation.SmoothRealTrivialization

/-!
# PoincareConjecture

Root module for the repository's primary, source-independent formalization.
-/
