import PoincareConjecture.Basic
import PoincareConjecture.Topology.FiberSaturation.NeckCoordinates
import PoincareConjecture.Topology.FiberSaturation.Boundary
import PoincareConjecture.Topology.FiberSaturation.ProductPairing
import PoincareConjecture.Topology.FiberSaturation.TorusComponents
import PoincareConjecture.Topology.FiberSaturation.TorusRegionClassification
import PoincareConjecture.Topology.FiberSaturation.BoundaryModels
import PoincareConjecture.Topology.FiberSaturation.SmoothEmbeddingModels
import PoincareConjecture.Topology.FiberSaturation.PresentedSmoothRegion
import PoincareConjecture.Topology.FiberSaturation.SmoothProductRegion

/-!
# PoincareConjecture

Root module for the repository's primary, source-independent formalization.
-/
