import PoincareConjecture.ParallelMath.Quantitative
import PoincareConjecture.ParallelMath
import PoincareConjecture.Topology.FiberSaturation.SmoothNeck.FiniteCutClosure
import PoincareConjecture.Topology.FiberSaturation.SmoothNeck.NativeCutClosure
import PoincareConjecture.Topology.FiberSaturation.SmoothCollar.ComplementClosure
import PoincareConjecture.Topology.FiberSaturation.DomainAtlas.CollarProductCoordinates
import PoincareConjecture.Topology.FiberSaturation.DomainAtlas.CollaredRegularOpen
import PoincareConjecture.Topology.FiberSaturation.DomainAtlas.ClosedDomain
import PoincareConjecture.Topology.FiberSaturation.CollarClosureChart
import PoincareConjecture.Topology.FiberSaturation.CollarClosureHalfSpace
import PoincareConjecture.Topology.FiberSaturation.ComplementaryBoundarySelection
import PoincareConjecture.Basic
import PoincareConjecture.Topology.FiberSaturation.SmoothPeriodicInverse
import PoincareConjecture.Topology.FiberSaturation.NeckCoordinates
import PoincareConjecture.Topology.FiberSaturation.Boundary
import PoincareConjecture.Topology.FiberSaturation.ProductPairing
import PoincareConjecture.Topology.FiberSaturation.TorusComponents
import PoincareConjecture.Topology.FiberSaturation.TorusRegionClassification
import PoincareConjecture.Topology.FiberSaturation.BoundaryModels
import PoincareConjecture.Topology.FiberSaturation.SmoothEmbeddingModels
import PoincareConjecture.Topology.FiberSaturation.PresentedSmoothRegion
import PoincareConjecture.Topology.FiberSaturation.SmoothProductRegion
import PoincareConjecture.Topology.FiberSaturation.AbstractBundleMappingTorus
import PoincareConjecture.Topology.FiberSaturation.AbstractBoundaryPairing
import PoincareConjecture.Topology.FiberSaturation.NativeCirclePullback
import PoincareConjecture.Topology.FiberSaturation.AbstractSmoothBundleRegion
import PoincareConjecture.Topology.FiberSaturation.RelativeNeckPairing

import PoincareConjecture.Topology.FiberSaturation.SmoothIntervalTrivialization

import PoincareConjecture.Topology.FiberSaturation.SmoothRealTrivialization

/-!
# PoincareConjecture

Root module for the repository's primary, source-independent formalization.
-/
